# Generated by Django 5.2.7 on 2025-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=200)),
                ('Item_desc', models.CharField(max_length=200)),
                ('Item_price', models.IntegerField()),
            ],
        ),
    ]
