# Generated by Django 5.2.7 on 2025-11-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=200)),
                ('Item_desc', models.CharField(max_length=200)),
                ('Item_price', models.IntegerField()),
                ('Item_image', models.CharField(default='https://th.bing.com/th/id/OIP.NULWEmlj4g8ASx3w_Ps7MQAAAA?w=155&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', max_length=500)),
            ],
        ),
    ]
